apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: other-service
  template:
    metadata:
      labels:
        app: other-service
    spec:
      containers:
        - name: other-service
          image: other-service:latest
          ports:
            - containerPort: 50053
          envFrom:
            - configMapRef:
                name: other-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: other-service
spec:
  selector:
    app: other-service
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
